package phase0

import (
	"fmt"
	"sort"
	"strings"
)

// RenderAdoption renders report/ADOPTION.md from per-network summaries.
// Every number in it comes from a Summary; nothing is typed in by hand.
func RenderAdoption(sums []Summary) string {
	sort.Slice(sums, func(i, j int) bool { return order(sums[i].Network) < order(sums[j].Network) })
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	p("# SEP-47 adoption report\n\n")
	p("Generated by `sep47idx phase0` from the per-network summaries in this directory. ")
	p("Every number below comes from those runs; the date of each run is given in its section.\n\n")
	p("A **declaration** is what a contract's `sep` meta says (SEP-47). An **interface match** compares its ")
	p("`contractspecv0` function types with a rule file. Neither says anything about behavior.\n\n")

	for _, s := range sums {
		if s.Network == "mainnet" {
			p("## Decision\n\n")
			p("Unique mainnet Wasm hashes declaring any SEP: **%s**. Applicable row of the CLAUDE.md §5.10 decision rule:\n\n", fmtRate(s.DeclaresAny.ByHash))
			p("> %s\n\n", s.Decision)
		}
	}

	for _, s := range sums {
		p("## %s\n\n", title(s.Network))
		p("Run: %s, latest ledger %d. Parser version %s; rules %s.\n\n", s.GeneratedAt, s.LatestLedger, s.ParserVersion, strings.Join(s.RulesetVersions, ", "))
		p("**Method.** %s\n\n", s.Method)

		p("### Contracts\n\n| | Count | Share |\n| --- | ---: | ---: |\n")
		total := s.Contracts.Total
		p("| Contracts counted | %d | |\n", total)
		p("| Stellar Asset Contracts | %d | %s |\n", s.Contracts.SAC, pct(s.Contracts.SAC, total))
		p("| Wasm (direct hash) | %d | %s |\n", s.Contracts.Wasm, pct(s.Contracts.Wasm, total))
		p("| Wasm by CAP-85 reference | %d | %s |\n", s.Contracts.WasmRef, pct(s.Contracts.WasmRef, total))
		p("| … distinct references they share | %d | |\n", s.Contracts.WasmRefDistinct)
		p("| … references unresolved | %d | |\n", s.Contracts.WasmRefUnresolved)
		switch ia := s.InstanceArchival; {
		case InstanceArchivalChecked(s):
			p("| Instances archived | %d | %s |\n", s.Contracts.ArchivedInstances, pct(s.Contracts.ArchivedInstances, total))
		case ia != nil:
			p("| Instances archived (measured by %s at ledger %d) | %d of %d | %s |\n", ia.Source, ia.Ledger, ia.Archived, ia.Of, pct(ia.Archived, ia.Of))
		default:
			p("| Instances archived | not measured: the census source carries no instance TTLs | |\n")
		}
		p("| Instance rows that failed to decode | %d | |\n", s.Contracts.InstanceDecodeErrors)
		p("| Wasm contracts whose code is archived or missing | %d | |\n", s.Contracts.Wasm+s.Contracts.WasmRef-s.Contracts.WasmRefUnresolved-s.Contracts.Measured)
		p("| Wasm contracts measured (by-contract denominator) | %d | |\n\n", s.Contracts.Measured)

		p("### Wasm hashes\n\n| | Count |\n| --- | ---: |\n")
		if s.Hashes.CodeEntries > 0 {
			p("| Code entries in census | %d |\n| … marked deleted | %d |\n", s.Hashes.CodeEntries, s.Hashes.CodeDeleted)
		}
		p("| Unique hashes measured for | %d |\n", s.Hashes.Population)
		p("| Archived or missing (not fetched) | %d |\n", s.Hashes.Archived)
		p("| Fetched (by-hash denominator) | %d |\n", s.Hashes.Measured)
		p("| … parsed fully / partly / not at all | %d / %d / %d |\n", s.Hashes.ParseOK, s.Hashes.ParsePartial, s.Hashes.ParseError)
		p("| … run by at least one contract | %d |\n\n", s.Hashes.UsedByContract)

		p("### Declarations (`sep` meta)\n\n| | By unique hash | By contract |\n| --- | ---: | ---: |\n")
		p("| Declares any SEP | %s | %s |\n", fmtRate(s.DeclaresAny.ByHash), fmtRate(s.DeclaresAny.ByContract))
		if s.DeclaresAny.Wilson95 != nil {
			p("\n95%% Wilson interval for the by-contract rate: %.2f%% to %.2f%%. ", s.DeclaresAny.Wilson95.Low, s.DeclaresAny.Wilson95.High)
			p("The interval covers sampling error only; the sample is drawn by activity (see Method), which it does not correct for.\n")
		}
		p("\nFactory deployments make many contracts share one hash, so the two columns can differ a lot.\n\n")
		if len(s.PerSEP) == 0 {
			p("No SEP number is declared.\n\n")
		} else {
			p("| SEP | Hashes | Contracts |\n| ---: | ---: | ---: |\n")
			for _, c := range s.PerSEP {
				p("| %d | %d | %d |\n", c.SEP, c.Hashes, c.Contracts)
			}
			p("\n")
		}

		p("### Anomalies in `sep` values\n\n")
		if len(s.Anomalies) == 0 {
			p("None found.\n\n")
		} else {
			p("| Anomaly | Tokens | Hashes | Examples |\n| --- | ---: | ---: | --- |\n")
			for _, a := range s.Anomalies {
				p("| `%s` | %d | %d | %s |\n", a.Code, a.Tokens, a.Hashes, strings.ReplaceAll(strings.Join(a.Examples, "; "), "|", "\\|"))
			}
			p("\n")
		}

		p("### Interface (`contractspecv0`)\n\nHashes with a spec section: %s.\n\n", fmtRate(s.WithSpec))
		p("SEP-41 matcher (rules %s), counted over fetched hashes and measured contracts:\n\n", strings.Join(s.RulesetVersions, ", "))
		p("| Status | Hashes | Contracts | Of which declare SEP-41 (hashes / contracts) |\n| --- | ---: | ---: | ---: |\n")
		for _, st := range []string{"match", "partial", "mismatch", "no_spec"} {
			c, d := s.SEP41.Status[st], s.SEP41.Declared41[st]
			p("| `%s` | %d | %d | %d / %d |\n", st, c.Hashes, c.Contracts, d.Hashes, d.Contracts)
		}
		p("\nOK-count histogram (hashes with a spec, by number of the %d required functions present with accepted types):\n\n", len(s.SEP41.OKHistogram)-1)
		p("| OK | %s |\n|%s\n| Hashes | %s |\n\n", joinInts(seq(len(s.SEP41.OKHistogram))), strings.Repeat(" ---: |", len(s.SEP41.OKHistogram)+1), joinInts(s.SEP41.OKHistogram))
		p("**Undeclared gap** (inferred): %d hashes / %d contracts match SEP-41's interface and declare nothing.\n\n", s.SEP41.UndeclaredGap.Hashes, s.SEP41.UndeclaredGap.Contracts)

		p("### Limits\n\nWasm ≤ %d bytes; requested section ≤ %d bytes; ≤ %d sections; XDR depth ≤ %d.\n\n",
			s.Limits.MaxWasmBytes, s.Limits.MaxSectionBytes, s.Limits.MaxSections, s.Limits.MaxXDRDepth)
		if s.Sample != nil {
			p("Sample: retention window %d–%d, %d strata, %d ledgers scanned, contracts per stratum %v, %d instance entries undecodable.\n\n",
				s.Sample.OldestLedger, s.Sample.LatestLedger, s.Sample.Strata, s.Sample.LedgersScanned, s.Sample.PerStratum, s.Sample.SkippedEntries)
		}
	}
	return b.String()
}

func order(n string) int {
	if n == "mainnet" {
		return 0
	}
	return 1
}

func title(n string) string {
	if n == "" {
		return n
	}
	return strings.ToUpper(n[:1]) + n[1:]
}

func fmtRate(r Rate) string { return fmt.Sprintf("%d / %d (%.2f%%)", r.N, r.Of, r.Pct) }

func pct(n, of int) string {
	if of == 0 {
		return "–"
	}
	return fmt.Sprintf("%.2f%%", 100*float64(n)/float64(of))
}

func seq(n int) []int {
	out := make([]int, n)
	for i := range out {
		out[i] = i
	}
	return out
}

func joinInts(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprint(x)
	}
	return strings.Join(parts, " | ")
}
